### ISSUE TITLE
Bridge Took My Coins

### ISSUE THREAD

**Issue by Kryo-Coin** [ton-blockchain/docs#19]
I transferred TonCoin from my desktop wallet to metamask the address showed up just fine no issues it allowed me to send the ton out but now 5 days later its saying its an invalid address shouldnt software know this before it allows it to be sent. on top of this you have no direct access for the bridge or support. I need to speak to someone about having these returned to sender wallet. My email is join.kryo@kryoVs.io
wallet: EQD-D7npZEYubyQ7pMuH3Tt9uKLbXzj1bvASRR82__hM7Sh9

**Comment by EmelyanenkoK** [comment]
Not suitable place for this topic. Official technical support: @ton_help_bot may help with that
