### ISSUE TITLE
Search button out of place

### ISSUE THREAD

**Issue by luccascomvoce** [ton-blockchain/docs#56]
On Android, using Brave Browser or Google Chrome, the "Search" button is misplaced.
![Screenshot_2022-10-09-03-09-55-870_com brave browser](https://user-images.githubusercontent.com/65538684/194740986-3c43a48b-8db2-4dc1-aec2-7b97b68dc284.jpg)
![Screenshot_2022-10-09-03-15-09-853_com android chrome](https://user-images.githubusercontent.com/65538684/194741168-cb1f34b1-9eb1-48fe-899e-47af234d9006.jpg)

Poco X3 Pro
MIUI 13.0.4
Android 12

**Comment by awesome-doge** [comment]
searching.ton's website, not part of ton-blockchain/docs (https://ton.org/docs/#/)
